create table if not exists public.growth_funnel_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  event_name text not null check (event_name in (
    'landing','form_started','route_ready','trip_ready',
    'quote_viewed','customer_started','ready_to_submit','booking_created'
  )),
  stage_order smallint not null check (stage_order between 1 and 8),
  occurred_at timestamptz not null default now(),
  acquisition_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  fbclid text,
  referral_code text,
  landing_page text,
  service_type text,
  airport_key text,
  vehicle_type text,
  quote_total numeric(12,2),
  booking_id uuid references public.bookings(id) on delete set null,
  constraint growth_funnel_events_session_event_unique unique (session_id, event_name)
);

create index if not exists growth_funnel_events_occurred_idx
  on public.growth_funnel_events (occurred_at desc);

create index if not exists growth_funnel_events_event_occurred_idx
  on public.growth_funnel_events (event_name, occurred_at desc);

create index if not exists growth_funnel_events_source_occurred_idx
  on public.growth_funnel_events (acquisition_source, occurred_at desc);

create index if not exists growth_funnel_events_session_stage_idx
  on public.growth_funnel_events (session_id, stage_order desc);

alter table public.growth_funnel_events enable row level security;

comment on table public.growth_funnel_events is
  'v4.3.1: anonimowy lejek publicznego formularza B2C. Bez nazwiska, telefonu, e-maila i adresu klienta.';
comment on column public.growth_funnel_events.session_id is
  'Losowy identyfikator jednej sesji formularza zapisany w sessionStorage.';
comment on column public.growth_funnel_events.stage_order is
  'Najdalszy osiągnięty etap można wyliczyć jako max(stage_order) dla session_id.';

notify pgrst, 'reload schema';
