"use client";
import { useEffect, useMemo, useState } from "react";
import { PRICES } from "@/lib/pricing";
type Suggestion={placeId?:string;text?:string};
export default function BookingForm(){
 const [serviceType,setServiceType]=useState("to_airport"),[address,setAddress]=useState(""),[airport,setAirport]=useState("balice"),[vehicleType,setVehicleType]=useState("car");
 const [passengers,setPassengers]=useState(1),[distanceKm,setDistanceKm]=useState(0),[routeMessage,setRouteMessage]=useState("Wpisz adres."),[suggestions,setSuggestions]=useState<Suggestion[]>([]);
 const [travelDate,setTravelDate]=useState(""),[travelTime,setTravelTime]=useState(""),[returnDate,setReturnDate]=useState(""),[returnTime,setReturnTime]=useState("");
 const [customerName,setCustomerName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[flightNumber,setFlightNumber]=useState(""),[returnFlightNumber,setReturnFlightNumber]=useState("");
 const [invoiceRequired,setInvoiceRequired]=useState(false),[companyName,setCompanyName]=useState(""),[companyNip,setCompanyNip]=useState(""),[companyAddress,setCompanyAddress]=useState(""),[notes,setNotes]=useState(""),[result,setResult]=useState("");
 useEffect(()=>{if(passengers>3)setVehicleType("bus")},[passengers]);
 useEffect(()=>{if(address.trim().length<3){setSuggestions([]);return}const t=setTimeout(async()=>{const r=await fetch(`/api/places?q=${encodeURIComponent(address)}`);const d=await r.json();setSuggestions(d.suggestions??[])},350);return()=>clearTimeout(t)},[address]);
 async function calculateRoute(a:string){setRouteMessage("Obliczanie trasy...");const r=await fetch("/api/route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address:a})});const d=await r.json();if(!r.ok){setRouteMessage(d.error??"Nie udało się obliczyć trasy.");setDistanceKm(0);return}setDistanceKm(d.distanceKm);setRouteMessage(`✓ ${d.distanceKm} km od bazy · ${d.billableKm} km płatne · dopłata ${Number(d.extraOneWay).toFixed(2)} zł`)}
 const quote=useMemo(()=>{const m=serviceType==="roundtrip"?2:1,row=PRICES[airport],base=row[vehicleType as "car"|"bus"]*m,b=Math.max(0,distanceKm-20),extra=b*2.4*m,sub=base+extra,vat=invoiceRequired?sub*.08:0;return{base,extra,vat,total:sub+vat}},[serviceType,airport,vehicleType,distanceKm,invoiceRequired]);
 const routeText=serviceType==="from_airport"?`${PRICES[airport].label} → ${address||"—"}`:serviceType==="roundtrip"?`${address||"—"} ↔ ${PRICES[airport].label}`:`${address||"—"} → ${PRICES[airport].label}`;
 async function submit(){setResult("Zapisywanie...");const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceType,address,airport,travelDate,travelTime,returnDate,returnTime,passengers,vehicleType,distanceKm,customerName,phone,email,flightNumber,returnFlightNumber,invoiceRequired,companyName,companyNip,companyAddress,notes})});const d=await r.json();setResult(r.ok?`Rezerwacja ${d.booking_number} zapisana. Kwota: ${Number(d.total_price).toFixed(2)} zł`:d.error??"Błąd zapisu.")}
 return <div className="layout"><div className="card"><span className="badge">MATT BOOKING PRO</span><h1>Zarezerwuj transfer lotniskowy</h1>
 <h3>Rodzaj przejazdu</h3><div className="choice-grid">{[["to_airport","🛫 Na lotnisko","Odbiór spod adresu i przejazd na lotnisko."],["from_airport","🛬 Z lotniska","Odbiór po przylocie i przejazd pod adres."],["roundtrip","🔁 W obie strony","Wyjazd oraz późniejszy odbiór."]].map(([k,t,d])=><button key={k} className={`choice ${serviceType===k?"active":""}`} onClick={()=>setServiceType(k)}><strong>{t}</strong><small>{d}</small></button>)}</div>
 <h3 style={{marginTop:24}}>Trasa</h3><div className="grid"><label>{serviceType==="from_airport"?"Adres docelowy":"Adres odbioru"}<input value={address} onChange={e=>{setAddress(e.target.value);setDistanceKm(0);setRouteMessage("Wybierz adres z podpowiedzi.")}} placeholder="np. ul. Pszczyńska 10, Żory"/>{suggestions.length>0&&<div className="suggestions">{suggestions.slice(0,5).map((s,i)=><button key={s.placeId??i} className="suggestion" onClick={()=>{const a=s.text??"";setAddress(a);setSuggestions([]);calculateRoute(a)}}>{s.text}</button>)}</div>}</label><label>{serviceType==="from_airport"?"Z którego lotniska odbieramy?":"Wybierz lotnisko"}<select value={airport} onChange={e=>setAirport(e.target.value)}>{Object.entries(PRICES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label></div><div className={`route-status ${distanceKm?"ok":""}`}>{routeMessage}</div>
 <h3 style={{marginTop:24}}>Termin i pojazd</h3><div className="grid"><label>{serviceType==="from_airport"?"Data przylotu":"Data wyjazdu"}<input type="date" value={travelDate} onChange={e=>setTravelDate(e.target.value)}/></label><label>{serviceType==="from_airport"?"Godzina przylotu":"Godzina odbioru"}<input type="time" value={travelTime} onChange={e=>setTravelTime(e.target.value)}/></label><label>Numer lotu<input value={flightNumber} onChange={e=>setFlightNumber(e.target.value)}/></label><label>Pasażerowie<select value={passengers} onChange={e=>setPassengers(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label>{serviceType==="roundtrip"&&<><label>Data powrotu<input type="date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label><label>Godzina przylotu powrotnego<input type="time" value={returnTime} onChange={e=>setReturnTime(e.target.value)}/></label><label>Numer lotu powrotnego<input value={returnFlightNumber} onChange={e=>setReturnFlightNumber(e.target.value)}/></label></>}<label>Pojazd<select value={vehicleType} onChange={e=>setVehicleType(e.target.value)}><option value="car" disabled={passengers>3}>Samochód osobowy</option><option value="bus">Bus do 8 osób</option></select></label></div>
 <h3 style={{marginTop:24}}>Dane klienta</h3><div className="grid"><label>Imię i nazwisko<input value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label><label>Telefon<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Faktura<select value={invoiceRequired?"1":"0"} onChange={e=>setInvoiceRequired(e.target.value==="1")}><option value="0">Nie</option><option value="1">Tak, dolicz 8%</option></select></label>{invoiceRequired&&<><label>Nazwa firmy<input value={companyName} onChange={e=>setCompanyName(e.target.value)}/></label><label>NIP<input value={companyNip} onChange={e=>setCompanyNip(e.target.value)}/></label><label>Adres firmy<input value={companyAddress} onChange={e=>setCompanyAddress(e.target.value)}/></label></>}<label>Uwagi<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label></div></div>
 <aside className="card summary"><h3>Podsumowanie live</h3><div className="row"><span>Trasa</span><strong>{routeText}</strong></div><div className="row"><span>Odległość</span><strong>{distanceKm?`${distanceKm} km`:"—"}</strong></div><div className="row"><span>Cena bazowa</span><strong>{quote.base.toFixed(2)} zł</strong></div><div className="row"><span>Dopłata</span><strong>{quote.extra.toFixed(2)} zł</strong></div><div className="row"><span>VAT</span><strong>{quote.vat.toFixed(2)} zł</strong></div><div className="row total"><span>Razem</span><strong>{quote.total.toFixed(2)} zł</strong></div><button className="btn" style={{width:"100%",marginTop:16}} onClick={submit}>ZAREZERWUJ</button>{result&&<p>{result}</p>}<p className="muted">Pilne rezerwacje: +48 691 242 691</p></aside></div>
}
